#!/usr/bin/python3
import random
number = random.randint(-10000, 10000)

print(number)
if number < 0:
    num =  number
else:
    num = (-1) * number

for i in range(5):
    if (num > 10):
        num = num % 10
if num > 5:
    print("Last digit of {:d} is {:d} and is greater than 5".format(number num))
elif num == 0:
    print("Last digit of {:d} is {:d} and is greater than 5".format(number num))
elif num < 6 and num != 0:
   print("Last digit of {:d} is {:d} and is greater than 6".format(number num))
