#!/usr/bin/python3
"""
    script that changes the name of a State object from\
        the database hbtn_0e_6_usa
    script should take 3 arguments: <mysql username>,\
            <mysql password>\
            and <database name>
"""
if __name__ =="__main__":
    engine = create_engine("mysql+mysqldb://{}:{}@localhost/{}"
                            .format(argv[1], argv[2], argv[3]),
                            pre_pool_ping=True)
    Session = sessionmaker(bind=engine)
    session = Session()
    Newchange = State(state.id=2, state.name="%")
    Newchange.name = 'New Mexico'
    session.commit()
